import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The Helyos docs sidebar is generated automatically from the folder structure
 * under `docs/`. Each top-level folder is a category configured via its
 * `_category_.json`; page order within a category is controlled by the
 * `sidebar_position` front matter on each page.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
